### ISSUE TITLE
Keychain GUI appears if an account other than the logged-in account is used to authenticate.

### ISSUE THREAD

**Issue by rtrouton** [google/macops#39]
I'm seeing an issue where, if I'm logged into a user account and click on a lock in System Preferences, then log in using another account's admin credentials, the Keychain Minder GUI pops up.

To reproduce:

1. Set up two accounts, where one has admin rights and the other does not.
2. Log in as the account that does not have admin rights.
3. Open System Preferences
4. Click a lock
5. Log into the authentication dialog using the account with admin rights' credentials.

Expected behavior:

A. Lock unlocks
B.  Keychain Minder GUI does not appear

Observed behavior:

1. Lock unlocks
2.  Keychain Minder GUI appears.

Note: I was also able to reproduce the behavior when both accounts had admin rights, but I figured the above scenario was the more common of the two.

**Comment by tburgin** [comment]
You may be able to check the session owner with:
```c
err = mechanism->fPlugin->fCallbacks->GetHintValue(mechanism->fEngine, "suggested-user", &value);
```

**Comment by pleasego2help** [comment]
Quick question relating to your above **No users with uids under 501**... 

As of Yosemite we switched from sub-501 accounts due to it causing (migration, ARD) issues, and since Apple updated their [support page](https://support.apple.com/en-us/HT203998) (removing sub-501 instructions) for Yosemite+, instead using 'dscl... IsHidden'. (I discovered the topic when I started using Yosemite+ 'sysadminctl' when creating local admin in deployment.)

[Original dev post](https://devforums.apple.com/message/711550#711550) (devforum login required, *slightly* humorous)
[Further Details](https://github.com/MagerValp/CreateUserPkg/issues/32) from MagerValp discussion using **createuserpkg**

(I apologize if this is out of context - please ignore if it is.)

**Comment by russellhancox** [comment]
This issue was moved to google/macops-keychainminder#2
